app_admin:
    resource: '@AppBundle/Controller/Admin'
    type: annotation
    prefix: "/admin"

app_front:
    resource: '@AppBundle/Controller/Front'
    type: annotation
    prefix: "/"

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"